async:
  # Set to true if you want scoreboards to run asynchronously
  enabled: true
  thread-pool:
    # If enabled, the load of updating scoreboards will be divided over X threads (with X being the size you set up)
    # If disabled (and async is enabled), then there will be a thread per scoreboard.
    # Changing the thread-pool settings will REQUIRE a restart to take effect (/hs reload will not have an effect)
    enabled: true
    size: 100