async:
  # Set to true if you want scoreboards to run asynchronously
  enabled: true
  thread-pool:
    # If enabled, the load of updating scoreboards will be divided over X threads (with X being the size you set up)
    # If disabled (and async is enabled), then there will be a thread per scoreboard.
    # Changing the thread-pool settings will REQUIRE a restart to take effect (/hs reload will not have an effect)
    enabled: true
    size: 100

scoreboards:
  - condition: 'default'
    title:
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      interval: 1
      # The frames of the title
      frames:
        - '&0&lHello World'
        - '&1&lHello World'
        - '&2&lHello World'
        - '&3&lHello World'
        - '&4&lHello World'
        - '&5&lHello World'
        - '&6&lHello World'
        - '&7&lHello World'
        - '&8&lHello World'
        - '&9&lHello World'
        - '&a&lHello World'
        - '&b&lHello World'
        - '&c&lHello World'
        - '&d&lHello World'
        - '&e&lHello World'
        - '&f&lHello World'
    lines:
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      - interval: 1
        # The frames of the line
        frames:
          - '&6Hello World'
          - '&eH&6ello World'
          - '&eHe&6llo World'
          - '&eHel&6lo World'
          - '&eHell&6o World'
          - '&eHello &6World'
          - '&eHello W&6orld'
          - '&eHello Wo&6rld'
          - '&eHello Wor&6ld'
          - '&eHello Worl&6d'
          - '&eHello World'
          - '&eHello World'
          - '&eHello World'
          - '&eHello Worl&6d'
          - '&eHello Wor&6ld'
          - '&eHello Wo&6rld'
          - '&eHello W&6orld'
          - '&eHello &6World'
          - '&eHell&6o World'
          - '&eHel&6lo World'
          - '&eHe&6llo World'
          - '&eH&6ello World'
          - '&6Hello World'
          - '&6Hello World'
          - '&6Hello World'
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      - interval: 1
        # The frames of the line
        frames:
          - '&2Hello World'
          - '&aH&2ello World'
          - '&aHe&2llo World'
          - '&aHel&2lo World'
          - '&aHell&2o World'
          - '&aHello &2World'
          - '&aHello W&2orld'
          - '&aHello Wo&2rld'
          - '&aHello Wor&2ld'
          - '&aHello Worl&2d'
          - '&aHello World'
          - '&aHello World'
          - '&aHello World'
          - '&aHello Worl&2d'
          - '&aHello Wor&2ld'
          - '&aHello Wo&2rld'
          - '&aHello W&2orld'
          - '&aHello &2World'
          - '&aHell&2o World'
          - '&aHel&2lo World'
          - '&aHe&2llo World'
          - '&aH&2ello World'
          - '&2Hello World'
          - '&2Hello World'
          - '&2Hello World'
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      - interval: 1
        # The frames of the line
        frames:
          - '&4Hello World'
          - '&cH&4ello World'
          - '&cHe&4llo World'
          - '&cHel&4lo World'
          - '&cHell&4o World'
          - '&cHello &4World'
          - '&cHello W&4orld'
          - '&cHello Wo&4rld'
          - '&cHello Wor&4ld'
          - '&cHello Worl&4d'
          - '&cHello World'
          - '&cHello World'
          - '&cHello World'
          - '&cHello Worl&4d'
          - '&cHello Wor&4ld'
          - '&cHello Wo&4rld'
          - '&cHello W&4orld'
          - '&cHello &4World'
          - '&cHell&4o World'
          - '&cHel&4lo World'
          - '&cHe&4llo World'
          - '&cH&4ello World'
          - '&4Hello World'
          - '&4Hello World'
          - '&4Hello World'
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      - interval: 1
        # The frames of the line
        frames:
          - '&9Hello World'
          - '&bH&9ello World'
          - '&bHe&9llo World'
          - '&bHel&9lo World'
          - '&bHell&9o World'
          - '&bHello &9World'
          - '&bHello W&9orld'
          - '&bHello Wo&9rld'
          - '&bHello Wor&9ld'
          - '&bHello Worl&9d'
          - '&bHello World'
          - '&bHello World'
          - '&bHello World'
          - '&bHello Worl&9d'
          - '&bHello Wor&9ld'
          - '&bHello Wo&9rld'
          - '&bHello W&9orld'
          - '&bHello &9World'
          - '&bHell&9o World'
          - '&bHel&9lo World'
          - '&bHe&9llo World'
          - '&bH&9ello World'
          - '&9Hello World'
          - '&9Hello World'
          - '&9Hello World'
      # The interval is in ticks, the lowest possible interval is 1 tick.
      # 1 tick = about 50 milliseconds, so 20 ticks = 1 second
      # Setting the interval to -1 will disable the animation.
      - interval: 1
        # The frames of the line
        frames:
          - '&5Hello World'
          - '&dH&5ello World'
          - '&dHe&5llo World'
          - '&dHel&5lo World'
          - '&dHell&5o World'
          - '&dHello &5World'
          - '&dHello W&5orld'
          - '&dHello Wo&5rld'
          - '&dHello Wor&5ld'
          - '&dHello Worl&5d'
          - '&dHello World'
          - '&dHello World'
          - '&dHello World'
          - '&dHello Worl&5d'
          - '&dHello Wor&5ld'
          - '&dHello Wo&5rld'
          - '&dHello W&5orld'
          - '&dHello &5World'
          - '&dHell&5o World'
          - '&dHel&5lo World'
          - '&dHe&5llo World'
          - '&dH&5ello World'
          - '&5Hello World'
          - '&5Hello World'
          - '&5Hello World'