name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
        release-branch-name: "master"
        
        git-release-bot-name: "Dieter Blancke"
        git-release-bot-email: "dieter.blancke@outlook.com"
        
        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
